site_name: SMART Health Cards Framework 日本語翻訳
repo_url: https://github.com/shuuji3/health-cards
edit_uri: 'edit/lang-ja/docs'


nav:
  - プロトコル: index.md
  - 証明書のモデル: credential-modeling.md
  - 証明書のタイプ: vocabulary.md
  - 実装例: examples/index.md
  - Changelog: changelog.md

theme:
  name: material
  language: ja

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 2
      toc_depth: 4
  - admonition:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - def_list:


plugins:
    - search

extra_javascript:
    - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
    - mermaid.js

extra_css:
    - style.css

extra:
  search:
    language: 'jp'
